### PR TITLE
Add getBindingType method to binary types

### PR DESCRIPTION
**Pull request by enumag**
Indeed this seems to fix the problem reported in https://github.com/ramsey/uuid/issues/179.

### CODE REVIEW

**Comment by enumag** [comment]
ping @ramsey

**Comment by ramsey** [comment]
Is there a way to add a test to verify that this solves the problem? I've been trying to think through how that would work without requiring a database.

**Comment by enumag** [comment]
@ramsey In the current implementation it's the database itself (or maybe the pdo pgsql driver) that raises the error. Which means you do need the database to write a failing test.

**Comment by enumag** [comment]
@ramsey Can we get this merged? I'd like to switch my app to binary uuids.

**Comment by ramsey** [comment]
Merged in and release tagged as 1.4.2. Thanks!

**Pull request merged**
