### PR TITLE
Soft dependency on Doctrine ORM

### PR DESCRIPTION
**Pull request by vudaltsov**
In one of the projects we are using `DBAL` only. So we were disappointed that `ramsey/uuid-doctrine` requires the whole ORM package we don't need. The hack is to use the [`replace`](https://getcomposer.org/doc/04-schema.md#replace) composer directive which feels hackish.

This change feels a bit dangerous. But I think that projects using ORM do/should require it explicitly in the root `composer.json` rather than rely on the fact that it's a second level dependency.

Also closes https://github.com/ramsey/uuid-doctrine/issues/63.

### CODE REVIEW

**Comment by andrew-demb** [comment]
Any chance, that this PR will be merged?

**Comment by snapshotpl** [comment]
@vudaltsov orm should appear also in `suggest` section
@ramsey can you look at this?

**Comment by vudaltsov** [comment]
@snapshotpl , why ORM should appear in the `suggest` section?
The question of using or not using ORM is completely orthogonal to a UUID DBAL type.

**Comment by garak** [comment]
> @snapshotpl , why ORM should appear in the `suggest` section?

Because ORM is actually used in generator.

**Comment by vudaltsov** [comment]
> Because ORM is actually used in generator.

I know that, but is it a valid reason to install Doctrine ORM just because the library has a bridge for it?
What is the point of such a suggestion?

Don't get me wrong, I am not strictly against the suggestion. I just cannot imagine a situation when it could make sense. AFAICS in this very case the decision to (not) install ORM is always driven by some architectural reasonings.

**Comment by snapshotpl** [comment]
I think the best solution for that is create separate repository for ORM stuff.

**Comment by garak** [comment]
@vudaltsov I think it's fair to suggest every dependency that could be needed

**Comment by ramsey** [comment]
Thank you for contributing! 🎉

**Pull request merged**
