### PR TITLE
add php 7.3 and 7.4 to travis

### PR DESCRIPTION
**Pull request by andreybolonin**

### CODE REVIEW

**Comment by garak** [comment]
Maybe 7.4 should be allowed to fail

**Comment by snapshotpl** [comment]
@andreybolonin php 7.4 is now stable

**Comment by andreybolonin** [comment]
@snapshotpl updated

**Comment by snapshotpl** [comment]
php 5.5 and 5.6 need older distro to make it works

**Comment by andreybolonin** [comment]
remove 5.4-5.6, because https://www.php.net/supported-versions.php

**Comment by garak** [comment]
> remove 5.4-5.6, because https://www.php.net/supported-versions.php

But you can't just remove them from travis, as long as composer.json allows such versions.

**Comment by ramsey** [comment]
I merged this in commit https://github.com/ramsey/uuid-doctrine/commit/7108b9bdfc5a2d53d536122235c30d7b5164fe22.

Thank you for contributing! 🎉

**Pull request closed without merging**
