### PR TITLE
Added generator for time-optimized UUIDs and documentation

### PR DESCRIPTION
**Pull request by Xymanek**
Based on https://github.com/ramsey/uuid/wiki/Ramsey%5CUuid-Codec's#store-uuid-in-an-optimized-way-for-innodb-orderedtimecodec

Not sure if the test is enough or not but I couldn't come up with anything else

### CODE REVIEW

**Comment by Xymanek** [comment]
I'll fix the code style in a bit, but I have no clue what's wrong with `UuidInterface::class`....

**Comment by ramsey** [comment]
The `::class` keyword was added in PHP 5.5, so that syntax error is expected in 5.4. See http://php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class

**Comment by Xymanek** [comment]
@ramsey Fixed CS and PHP 5.4. On travis only HHVM is failing with cryptic message: 

> HHVM is no longer supported on Ubuntu Precise. Please consider using Trusty with `dist: trusty`.

**Comment by ramsey** [comment]
Thanks. I'll probably remove HHVM testing support; many other projects are already doing so.

**Comment by Xymanek** [comment]
Yeah, just read an hour ago that symfony is dropping it as well. Glad I could help

**Comment by ramsey** [comment]
Feel free to go ahead and remove it in this PR. :smile:

**Comment by Xymanek** [comment]
@ramsey Done

**Comment by boesing** [comment]
Is there anything whats missing for merge? Would like to use this. 👍

**Comment by ramsey** [comment]
Thanks for the reminder. Merging.

Thanks again for contributing!

**Pull request merged**
