### PR TITLE
Actually check that __toString method exists

### PR DESCRIPTION
**Pull request by teohhanhui**
Check before we try to cast to string.

### CODE REVIEW

**Comment by teohhanhui** [comment]
Fixed.

**Comment by ramsey** [comment]
The build is failing because the line is too long. Do you mind breaking that statement into multiple lines?

**Comment by teohhanhui** [comment]
I've split it into multiple lines, but do you prefer trailing conditionals or the other way round? :)

**Comment by ramsey** [comment]
The way you've formatted it is fine.

Oops! One more error:

```
 84 | ERROR | [x] Expected 0 spaces after opening bracket; newline
    |       |     found
    |       |     (PSR2.ControlStructures.ControlStructureSpacing.SpacingAfterOpenBrace)
```

You can run `composer test` locally before pushing to see what all the build will complain on, if there are errors.

**Comment by teohhanhui** [comment]
I think we need to update the phpcs rule. I'm following the draft PSR-12: https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md#51-if-elseif-else

> Expressions in parentheses MAY be split across multiple lines, where each subsequent line is indented at least once. When doing so, the first condition MUST be on the next line. The closing parenthesis and opening brace MUST be placed together on their own line with one space between them. Boolean operators between conditions MUST always be at the beginning or at the end of the line, not a mix of both.
>
> ```php
> <?php
>
> if (
>     $expr1
>     && $expr2
> ) {
>     // if body
> } elseif (
>     $expr3
>     && $expr4
> ) {
>     // elseif body
> }

**Comment by teohhanhui** [comment]
Anyway, that phpcs rule is wrong. PSR2 does not care if you add a newline. It only cares about space: https://www.php-fig.org/psr/psr-2/#5-control-structures

> There MUST NOT be a space after the opening parenthesis

**Comment by ramsey** [comment]
> There MUST NOT be a space after the opening parenthesis

A newline character is technically a space character. :smile:

At any rate, I have updated the project to use PHP CodeSniffer 3.3.1 and the new PSR-12 sniffs. Unfortunately, phpcs currently has a bug with the specific rule that covers control structure spacing, so I'm ignoring that rule for now:

* https://github.com/squizlabs/PHP_CodeSniffer/issues/2113
* 1be7a854f97f7d5828cf92a4b17d632902bb2e53

Thanks for your contribution! 🎉

**Comment by ramsey** [comment]
Oops! Now, it should be passing on Travis CI. f139239d39dfa0ac1e147ca89a179e8bdc44bda5

:smile:

**Comment by teohhanhui** [comment]
> A newline character is technically a space character.

Space is space. Whitespace is whitespace. Space is whitespace yes, but whitespace is not space. 😂

**Pull request merged**
